import type { CharacterDef } from "./types";

export const CHARACTERS: CharacterDef[] = [
  {
    id: "nancy",
    name: "Nancy",
    role: "Daughter",
    age: "14",
    bio: "A Brooklyn girl whose sass is armour for grief. The Orb answers her most strongly.",
    playstyle: "Stealth, empathy, Orb puzzles, talking her way through danger.",
    portrait: "/art/nancy.jpg?v=front",
  },
  {
    id: "ronnie",
    name: "Ronnie",
    role: "Father",
    age: "Professor",
    bio: "A protective dad who took Nancy to Israel to honour Sarah. Love is his power.",
    playstyle: "Protection, investigation, shielding Nancy, historical clues.",
    portrait: "/art/ronnie.jpg?v=cover",
  },
  {
    id: "veronika",
    name: "Veronika",
    role: "Of Nevaeh",
    age: "Elysium",
    bio: "Wife of Adamus. She knows the Grail's true purpose and the cost of creation.",
    playstyle: "Guidance, harmony, light-weaving, opening paths between worlds.",
    portrait: "/art/veronika-young.jpg?v=1",
  },
  {
    id: "sarah",
    name: "Sarah",
    role: "Mother",
    age: "Light",
    bio: "Nancy's mother. Love that can become solid on Nevaeh.",
    playstyle: "Memory, warmth, the family day that still belongs to them.",
    portrait: "/art/codex/sarah.jpg",
  },
  {
    id: "adamus",
    name: "Adamus",
    role: "Master Builder",
    age: "Nevaeh",
    bio: "Creator of the new universe and father of Sananda. Love as creation.",
    playstyle: "Time, craft, opening a sky without building a cage.",
    portrait: "/art/adamus.jpg?v=front",
  },
  {
    id: "mira",
    name: "Mira",
    role: "Sister of Veronika",
    age: "Nevaeh",
    bio: "Quiet competence in the gardens and halls of Nevaeh.",
    playstyle: "Preparation, gardens, a place ready before the bridge thins.",
    portrait: "/art/codex/mira.jpg",
  },
  {
    id: "sananda",
    name: "Sananda",
    role: "The Teacher",
    age: "33 AD",
    bio: "Son of Adamus. He left the Spark at Qumran so a later child could find it without an army.",
    playstyle: "Teaching, mercy, love first so the rest can follow.",
    portrait: "/art/codex/sananda.jpg",
  },
  {
    id: "zorath",
    name: "Zorath",
    role: "The rival",
    age: "Elysium",
    bio: "Jealous and ambitious. Father of Samael. A twisted love of possession.",
    playstyle: "Claim, title, wanting the new universe as a prize.",
    portrait: "/art/codex/zorath.jpg",
  },
  {
    id: "samael",
    name: "Samael",
    role: "Ancient shadow",
    age: "Patient",
    bio: "Son of Zorath. Dangerous and intelligent. Wants the Orb to control both worlds.",
    playstyle: "Division, patience, tools that keep people apart.",
    portrait: "/art/samael.jpg?v=front",
  },
  {
    id: "tux",
    name: "Tux",
    role: "Crew of Genesis",
    age: "Transit",
    bio: "Steady hands on a living ship. He watches the hull as if it were a person.",
    playstyle: "Listening, hull-sense, quiet transit.",
    portrait: "/art/codex/tux.jpg",
  },
  {
    id: "murphy",
    name: "Murphy",
    role: "Crew of Genesis",
    age: "Crew",
    bio: "Kin to the Chapter House. Earth humour in deep sky.",
    playstyle: "Crew work, family rope, keeping wonder grounded.",
    portrait: "/art/codex/murphy.jpg",
  },
  {
    id: "milo",
    name: "Milo",
    role: "Crew of Genesis",
    age: "Wonder",
    bio: "The one who still gasps at purple clouds. Wonder is a sensor.",
    playstyle: "Noticing light before instruments do.",
    portrait: "/art/codex/milo.jpg",
  },
  {
    id: "lena",
    name: "Lena",
    role: "Crew of Genesis",
    age: "Officer",
    bio: "Charts and courage. She treats the Sphalerizer with respect and people with more.",
    playstyle: "Navigation, folding space, folding a frightened heart.",
    portrait: "/art/codex/lena.jpg",
  },
  {
    id: "eliav",
    name: "Eliav",
    role: "Desert guardian",
    age: "Qumran",
    bio: "A keeper of old places. He knows which caves remember a Teacher.",
    playstyle: "Guardianship, silence, pointing without advertising.",
    portrait: "/art/codex/eliav.jpg",
  },
  {
    id: "nadav",
    name: "Nadav",
    role: "Desert companion",
    age: "Qumran",
    bio: "Younger watch over the same dust. Good manners toward mystery.",
    playstyle: "Messages, water, not touching what glows.",
    portrait: "/art/codex/nadav.jpg",
  },
  {
    id: "harlan",
    name: "Brother Peters",
    role: "Chapter House",
    age: "Grizzly",
    bio: "A door that still opens in the Catskills. He feeds people before he questions them.",
    playstyle: "Stone watch, warmth, a house that stays.",
    portrait: "/art/codex/grizzly.jpg",
  },
  {
    id: "geraldine",
    name: "Geraldine",
    role: "FBI",
    age: "Agent",
    bio: "Federal agent with a buzz cut. Practical. She treats the extraordinary as a job that still has to be done well.",
    playstyle: "Clean questions, case files, standing the line.",
    portrait: "/art/codex/geraldine.jpg?v=fbi",
  },
  {
    id: "olivia",
    name: "Olivia",
    role: "Open door",
    age: "Friend",
    bio: "A friend who notices when Nancy goes quiet.",
    playstyle: "Showing up, extra bread, ordinary courage.",
    portrait: "/art/codex/olivia.jpg",
  },
  {
    id: "rosie",
    name: "Rosie",
    role: "Loyal watch",
    age: "Friend",
    bio: "The friend who remembers the details others drop.",
    playstyle: "Names, dates, memory as protection.",
    portrait: "/art/codex/rosie.jpg",
  },
  {
    id: "sophie",
    name: "Sophie",
    role: "Soft armour",
    age: "Friend",
    bio: "Gentle, and therefore brave in the small hours.",
    playstyle: "Sitting until morning is possible again.",
    portrait: "/art/codex/sophie.jpg",
  },
];
