import type { CodexEntry, TimelineBeat } from "./types";

export const MAJOR_TABS: { id: string; tab: string }[] = [
  { id: "nancy", tab: "Nancy" },
  { id: "ronnie", tab: "Ronnie" },
  { id: "sarah", tab: "Sarah" },
  { id: "adamus", tab: "Adamus" },
  { id: "veronika", tab: "Veronika" },
  { id: "mira", tab: "Mira" },
  { id: "sananda", tab: "Sananda" },
  { id: "zorath", tab: "Zorath" },
  { id: "samael", tab: "Samael" },
];

export const MAJOR_IDS = new Set(MAJOR_TABS.map((t) => t.id));

export const ENTRIES: CodexEntry[] = [
  {
    id: "elysium",
    kind: "world",
    name: "Elysium",
    epithet: "The dying abundance",
    art: "/art/codex/elysium.jpg",
    summary: "A world that solved hunger, pain, and want, then learned that kindness without freedom becomes a noose.",
    body: "Crystal arcologies still shine. Gardens never fail. The people inside them grew tired of being perfect. From that fatigue came the hunger for a wilder twin, and the civil war that followed.",
    links: [
      { id: "adamus", label: "Adamus" },
      { id: "zorath", label: "Zorath" },
      { id: "first-world", label: "The First World" },
    ],
  },
  {
    id: "first-world",
    kind: "world",
    name: "The First World",
    epithet: "An empty universe given time",
    art: "/art/codex/first-world.jpg",
    summary: "Adamus did not decorate an old sky. He opened an empty universe, then gave it the dimension of time.",
    body: "Without time, love has nowhere to grow and grief has nowhere to heal. The First World is that gift: space enough for sister worlds, and a clock so choice can mean something.",
    links: [
      { id: "adamus", label: "Adamus" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "earth", label: "Earth" },
    ],
  },
  {
    id: "nevaeh",
    kind: "world",
    name: "Nevaeh",
    epithet: "Heaven spelled backwards",
    art: "/art/valley.jpg",
    summary: "A perfected sister world in the Pleiades, four hundred and forty-four light-years from Earth.",
    body: "Purple clouds. Rivers of light. Harmony, and an immortality of spirit that is earned rather than granted. It is not a prize. It is a home that answers only those who come with open hands.",
    links: [
      { id: "earth", label: "Earth" },
      { id: "bridge", label: "The Bridge" },
      { id: "veronika", label: "Veronika" },
      { id: "adamus", label: "Adamus" },
    ],
  },
  {
    id: "earth",
    kind: "world",
    name: "Earth / Terra",
    epithet: "The wilder twin",
    art: "/art/kitchen.jpg",
    extraArt: "/art/cave.jpg",
    summary: "Free will. Mortality. Trial. Brooklyn kitchens, Qumran caves, Roman dust, and the present day.",
    body: "Love here costs something. That is the point. The Chapter House in the Catskills still keeps watch. The desert remembers what cities forget. A girl from Brooklyn can change both worlds because she does not try to own them.",
    links: [
      { id: "nevaeh", label: "Nevaeh" },
      { id: "nancy", label: "Nancy" },
      { id: "orb", label: "The Orb" },
      { id: "grizzly", label: "Brother Peters" },
    ],
  },
  {
    id: "bridge",
    kind: "world",
    name: "The Bridge",
    epithet: "Opened by pure intent",
    art: "/art/bridge.jpg",
    summary: "Not a machine. A living link between Earth and Nevaeh.",
    body: "It will not answer a closed hand. When it opens, it is a gold thread you can almost hear. Power has tried for centuries. Love finished the work in an afternoon.",
    links: [
      { id: "earth", label: "Earth" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "orb", label: "The Orb" },
      { id: "theme-love", label: "Love that crosses worlds" },
    ],
  },

  {
    id: "nancy",
    kind: "character",
    name: "Nancy",
    epithet: "Girl of Nevaeh. Line of Fire.",
    art: "/art/nancy.jpg?v=front",
    group: "family",
    summary: "Fourteen. Orb bearer. Grief and unbreakable love.",
    body: "A Brooklyn girl whose sass is armour. She found the Orb in a Qumran cave and learned the only command it truly loves: let it heal. The Spark answers her most strongly because she asks for others first.",
    relations: "Daughter of Ronnie and Sarah. Bearer of the Orb. Friend to the crew of Genesis when the bridge is thin.",
    loveLine: "I will not let the dark have the last word.",
    links: [
      { id: "ronnie", label: "Ronnie" },
      { id: "sarah", label: "Sarah" },
      { id: "orb", label: "The Orb" },
      { id: "earth", label: "Earth" },
    ],
  },
  {
    id: "ronnie",
    kind: "character",
    name: "Ronnie",
    epithet: "Father. Professor. Shield.",
    art: "/art/ronnie.jpg?v=cover",
    group: "family",
    summary: "Nancy's father. Protective love is the power he actually has.",
    body: "He took Nancy to Israel to honour Sarah. He would rather stand in a doorway than hold a weapon. History is his language. His daughter is his north.",
    relations: "Husband of Sarah. Father of Nancy. Guest of the Chapter House when the old watch still opens a door.",
    loveLine: "If love can walk between worlds, I will walk it with her.",
    links: [
      { id: "nancy", label: "Nancy" },
      { id: "sarah", label: "Sarah" },
      { id: "theme-father", label: "Father to child" },
      { id: "grizzly", label: "Brother Peters" },
    ],
  },
  {
    id: "sarah",
    kind: "character",
    name: "Sarah",
    epithet: "The light that can become solid",
    art: "/art/codex/sarah.jpg",
    group: "family",
    summary: "Nancy's mother. She died of cancer. On Nevaeh she appears as spiritual light that love can briefly make solid.",
    body: "She is not a ghost story. She is a continuation. The family used to save one ordinary day and say it out loud so grief would not steal the calendar. That sentence still works.",
    relations: "Wife of Ronnie. Mother of Nancy. A presence on Nevaeh when the bridge is kind.",
    loveLine: "Tomorrow we are doing nothing.",
    links: [
      { id: "nancy", label: "Nancy" },
      { id: "ronnie", label: "Ronnie" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "theme-grief", label: "Grief and healing" },
    ],
  },
  {
    id: "adamus",
    kind: "character",
    name: "Adamus",
    epithet: "Master Builder",
    art: "/art/adamus.jpg?v=front",
    group: "nevaeh",
    summary: "Creator of the new universe and father of Sananda. Love as creation.",
    body: "He built because love needed room. He is not a king of worlds. He is a craftsman who knows that a perfect cage is still a cage, which is why Terra was seeded wild.",
    relations: "Husband of Veronika. Father of Sananda. Opposite of Zorath's hunger to possess.",
    loveLine: "I built a universe so love would have time.",
    links: [
      { id: "veronika", label: "Veronika" },
      { id: "sananda", label: "Sananda" },
      { id: "first-world", label: "The First World" },
      { id: "mira", label: "Mira" },
    ],
  },
  {
    id: "veronika",
    kind: "character",
    name: "Veronika",
    epithet: "Of Nevaeh",
    art: "/art/veronika-young.jpg?v=1",
    group: "nevaeh",
    summary: "Wife of Adamus. Steadiness and compassion.",
    body: "She knows the Grail's true purpose and the cost of creation. Where Adamus opens a sky, Veronika keeps the table set. Harmony is a practice, not a mood.",
    relations: "Wife of Adamus. Sister of Mira. Mother of Sananda.",
    loveLine: "Creation needs a hand that stays.",
    links: [
      { id: "adamus", label: "Adamus" },
      { id: "mira", label: "Mira" },
      { id: "sananda", label: "Sananda" },
      { id: "grail", label: "The Grail" },
    ],
  },
  {
    id: "mira",
    kind: "character",
    name: "Mira",
    epithet: "Sister of Veronika",
    art: "/art/codex/mira.jpg",
    group: "nevaeh",
    summary: "Veronika's sister. Quiet competence in the gardens and halls of Nevaeh.",
    body: "She tends what others invent. When the bridge thins, Mira is the one who has already prepared a place to land.",
    relations: "Sister of Veronika. Aunt-figure to Sananda's line. Friend to the crew when Genesis docks in light.",
    loveLine: "I keep the quiet places ready.",
    links: [
      { id: "veronika", label: "Veronika" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "genesis", label: "Genesis" },
    ],
  },
  {
    id: "sananda",
    kind: "character",
    name: "Sananda",
    epithet: "The Teacher of 33 AD",
    art: "/art/codex/sananda.jpg",
    group: "nevaeh",
    summary: "Son of Adamus. Love for humankind.",
    body: "He walked Terra in a hard century and left the Spark at Qumran so a later child could find it without an army. His teaching is simple enough to survive empires: love first.",
    relations: "Son of Adamus and Veronika. Brother in spirit to every guardian who kept the cave.",
    loveLine: "Teach them how to love. The rest will follow.",
    links: [
      { id: "adamus", label: "Adamus" },
      { id: "orb", label: "The Orb" },
      { id: "earth", label: "Earth" },
      { id: "eliav", label: "Eliav" },
    ],
  },
  {
    id: "zorath",
    kind: "character",
    name: "Zorath",
    epithet: "The rival",
    art: "/art/codex/zorath.jpg",
    group: "shadow",
    summary: "Jealous. Ambitious. Father of Samael. A twisted love of possession.",
    body: "He wanted the new universe as a prize, not a garden. Where Adamus gives time, Zorath wants title. His son inherited the hunger and refined it.",
    relations: "Father of Samael. Rival of Adamus. Old wound of Elysium's civil war.",
    loveLine: "What I cannot keep, I will not share.",
    links: [
      { id: "samael", label: "Samael" },
      { id: "adamus", label: "Adamus" },
      { id: "elysium", label: "Elysium" },
    ],
  },
  {
    id: "samael",
    kind: "character",
    name: "Samael",
    epithet: "Ancient shadow",
    art: "/art/codex/samael-human.jpg",
    extraArt: "/art/samael.jpg?v=front",
    group: "shadow",
    summary: "Son of Zorath. Patient. Dangerous. Wants control.",
    body: "He claims he invented tools of division, including the loud nets people now carry in their pockets, to keep humanity fractured. A failure in a century of swords once slipped his grip. He does not name it. Obsidian shows what he is when he stops pretending.",
    relations: "Son of Zorath. Enemy of the Orb's true purpose. A student of fracture.",
    loveLine: "Division is a tool. I prefer it to chance.",
    links: [
      { id: "zorath", label: "Zorath" },
      { id: "glasses", label: "Obsidian lenses" },
      { id: "theme-intent", label: "Intent versus control" },
      { id: "nancy", label: "Nancy" },
    ],
  },
  {
    id: "tux",
    kind: "character",
    name: "Tux",
    epithet: "Crew of Genesis",
    art: "/art/codex/tux.jpg",
    group: "crew",
    summary: "Steady hands on a living ship.",
    body: "He speaks little and watches the hull as if it were a person, because it is. Transit is not flying. It is listening.",
    relations: "Crew with Murphy, Milo, and Lena. Answers to the ship's mood as much as to any chart.",
    loveLine: "If she is quiet, we are on course.",
    links: [
      { id: "genesis", label: "Genesis" },
      { id: "murphy", label: "Murphy" },
      { id: "sphalerizer", label: "Sphalerizer" },
    ],
  },
  {
    id: "murphy",
    kind: "character",
    name: "Murphy",
    epithet: "Crew of Genesis",
    art: "/art/codex/murphy.jpg",
    group: "crew",
    summary: "Kin to the Chapter House line.",
    body: "He carries Earth humour into deep sky and keeps Milo from floating off into wonder. Family is a long rope. He holds his end.",
    relations: "Crew of Genesis. Kin to Brother Peters.",
    loveLine: "Home is whoever you refuse to lose.",
    links: [
      { id: "grizzly", label: "Brother Peters" },
      { id: "genesis", label: "Genesis" },
      { id: "milo", label: "Milo" },
    ],
  },
  {
    id: "milo",
    kind: "character",
    name: "Milo",
    epithet: "Crew of Genesis",
    art: "/art/codex/milo.jpg",
    group: "crew",
    summary: "The one who still gasps at purple clouds.",
    body: "Wonder is not naivety on Genesis. It is a sensor. Milo notices when the light changes before the instruments do.",
    relations: "Crew with Tux, Murphy, and Lena.",
    loveLine: "If it is beautiful, it is probably telling the truth.",
    links: [
      { id: "lena", label: "Lena" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "genesis", label: "Genesis" },
    ],
  },
  {
    id: "lena",
    kind: "character",
    name: "Lena",
    epithet: "Crew of Genesis",
    art: "/art/codex/lena.jpg",
    group: "crew",
    summary: "Officer of a living ship. Charts and courage in equal measure.",
    body: "She treats the Sphalerizer with respect and people with more. Folding space is easy beside folding a frightened heart.",
    relations: "Crew of Genesis. Often the voice that decides when to wait.",
    loveLine: "We arrive together, or we do not arrive.",
    links: [
      { id: "genesis", label: "Genesis" },
      { id: "sphalerizer", label: "Sphalerizer" },
      { id: "tux", label: "Tux" },
    ],
  },
  {
    id: "eliav",
    kind: "character",
    name: "Eliav",
    epithet: "Desert guardian",
    art: "/art/codex/eliav.jpg",
    group: "earth",
    summary: "A keeper of old places near Qumran.",
    body: "He knows which caves are only stone and which ones remember a Teacher. He does not advertise the difference.",
    relations: "Companion of Nadav. Watcher in the line that began when the Spark was left behind.",
    loveLine: "Some doors are kept by sitting still.",
    links: [
      { id: "nadav", label: "Nadav" },
      { id: "orb", label: "The Orb" },
      { id: "sananda", label: "Sananda" },
    ],
  },
  {
    id: "nadav",
    kind: "character",
    name: "Nadav",
    epithet: "Desert companion",
    art: "/art/codex/nadav.jpg",
    group: "earth",
    summary: "Younger watch over the same dust Eliav loves.",
    body: "He runs messages, carries water, and has the sense not to touch what glows. Guardianship is often just good manners toward mystery.",
    relations: "Companion of Eliav. Friend to strangers who come with grief instead of maps.",
    loveLine: "If they are kind, the desert can be kind too.",
    links: [
      { id: "eliav", label: "Eliav" },
      { id: "earth", label: "Earth" },
    ],
  },
  {
    id: "grizzly",
    kind: "character",
    name: "Brother Peters",
    epithet: "Grizzly",
    art: "/art/codex/grizzly.jpg",
    group: "earth",
    summary: "Stone Chapter House. A door that still opens.",
    body: "The Catskills keep an old watch in a house of stone. Grizzly stays. He is warm, and difficult to move. He feeds people before he questions them.",
    relations: "Kin to Murphy. Host to Ronnie and Nancy when the Orb needs a quiet room.",
    loveLine: "Sit. Eat. Then we will talk about heaven.",
    links: [
      { id: "murphy", label: "Murphy" },
      { id: "ronnie", label: "Ronnie" },
      { id: "earth", label: "Earth" },
    ],
  },
  {
    id: "geraldine",
    kind: "character",
    name: "Geraldine",
    epithet: "FBI",
    art: "/art/codex/geraldine.jpg?v=fbi",
    group: "earth",
    summary: "Federal agent. Practical. Watches the line between Brooklyn and what Earth is not ready to name.",
    body: "She works cases that do not fit a filing cabinet. When Nancy, Ronnie, and Sarah step into something older than a precinct, she does not look away. She asks clean questions, keeps people fed, and treats the extraordinary as a job that still has to be done well.",
    relations: "Federal ally to Nancy, Ronnie, and Sarah. A fixed star in Brooklyn weather.",
    loveLine: "You can save the world after you have told me the truth.",
    links: [
      { id: "sarah", label: "Sarah" },
      { id: "nancy", label: "Nancy" },
      { id: "theme-father", label: "Family motif" },
    ],
  },
  {
    id: "olivia",
    kind: "character",
    name: "Olivia",
    epithet: "Open door",
    art: "/art/codex/olivia.jpg",
    group: "earth",
    summary: "A friend who notices when Nancy goes quiet.",
    body: "Not every guardian wears a robe. Some send a message and show up with extra bread.",
    relations: "Friend in the Earth circle with Rosie and Sophie.",
    loveLine: "I can stay. That is the whole plan.",
    links: [
      { id: "rosie", label: "Rosie" },
      { id: "sophie", label: "Sophie" },
      { id: "nancy", label: "Nancy" },
    ],
  },
  {
    id: "rosie",
    kind: "character",
    name: "Rosie",
    epithet: "Loyal watch",
    art: "/art/codex/rosie.jpg",
    group: "earth",
    summary: "The friend who remembers the details others drop.",
    body: "She keeps names, dates, and the last kind thing Sarah said. Memory is a form of protection.",
    relations: "Friend with Olivia and Sophie.",
    loveLine: "I will hold this so you do not have to, for a while.",
    links: [
      { id: "olivia", label: "Olivia" },
      { id: "sophie", label: "Sophie" },
    ],
  },
  {
    id: "sophie",
    kind: "character",
    name: "Sophie",
    epithet: "Soft armour",
    art: "/art/codex/sophie.jpg",
    group: "earth",
    summary: "Gentle, and therefore brave in the small hours.",
    body: "She does not fight shadows with speeches. She sits on the end of a bed until morning is possible again.",
    relations: "Friend with Olivia and Rosie.",
    loveLine: "You do not have to be impressive to be loved.",
    links: [
      { id: "olivia", label: "Olivia" },
      { id: "rosie", label: "Rosie" },
      { id: "theme-grief", label: "Grief and healing" },
    ],
  },

  {
    id: "grail",
    kind: "artefact",
    name: "Grail of Desire",
    epithet: "G.O.D.",
    art: "/art/codex/grail.jpg",
    summary: "A living resonance chamber of intent. Not a cup for kings.",
    body: "It answers what you are, not what you claim. Large acts cost emotional fire. Small healings are almost free, which tells you what the chamber was built for.",
    links: [
      { id: "orb", label: "The Orb" },
      { id: "veronika", label: "Veronika" },
      { id: "theme-intent", label: "Pure intent" },
    ],
  },
  {
    id: "orb",
    kind: "artefact",
    name: "The Orb",
    epithet: "The Spark",
    art: "/art/orb.jpg?v=front",
    summary: "Portable heart of the Grail. It answers only pure selfless intent.",
    body: "Healing is freer. World-changing acts cost emotional fire. Nancy found it in the cave at Qumran where Sananda left it, not as a weapon, as a chance.",
    links: [
      { id: "grail", label: "The Grail" },
      { id: "nancy", label: "Nancy" },
      { id: "sananda", label: "Sananda" },
      { id: "bridge", label: "The Bridge" },
    ],
  },
  {
    id: "glasses",
    kind: "artefact",
    name: "Obsidian Lenses",
    epithet: "True faces",
    art: "/art/glasses.jpg",
    extraArt: "/art/samael.jpg?v=front",
    summary: "Volcanic glass that shows the faces the Shadow has worn.",
    body: "Samael is patient in a coat. The lenses do not care about coats. They care about the shape of a will. Look once. Then decide whether to be afraid or to heal anyway.",
    links: [
      { id: "samael", label: "Samael" },
      { id: "theme-intent", label: "Control" },
    ],
  },
  {
    id: "genesis",
    kind: "artefact",
    name: "Genesis",
    epithet: "The living ship",
    art: "/art/codex/genesis.jpg",
    summary: "More grown than built. A hull that listens.",
    body: "Genesis carries the crew between sister worlds when the bridge is not yet a road. You do not steer her so much as ask, and wait for the yes.",
    links: [
      { id: "tux", label: "Tux" },
      { id: "lena", label: "Lena" },
      { id: "sphalerizer", label: "Sphalerizer" },
      { id: "nevaeh", label: "Nevaeh" },
    ],
  },
  {
    id: "sphalerizer",
    kind: "artefact",
    name: "Sphalerizer",
    epithet: "Fold of space and time",
    art: "/art/codex/sphalerizer.jpg",
    summary: "Folds space and creates time dilation.",
    body: "Over four hundred and forty-four light-years, about five hundred Earth years pass for each week of transit. That is why love on Terra can look like absence, and still be on the way.",
    links: [
      { id: "genesis", label: "Genesis" },
      { id: "nevaeh", label: "Nevaeh" },
      { id: "earth", label: "Earth" },
    ],
  },

  {
    id: "theme-father",
    kind: "theme",
    name: "Father to child",
    epithet: "The first bridge",
    art: "/art/photo.jpg?v=family3",
    summary: "A parent standing in a doorway is already a cosmology.",
    body: "Ronnie's power is not scholarship. It is staying. Adamus built a universe. Both acts are the same shape: make room, then keep watch. The family used to keep one ordinary day as a promise. Tomorrow we are doing nothing.",
    links: [
      { id: "ronnie", label: "Ronnie" },
      { id: "nancy", label: "Nancy" },
      { id: "adamus", label: "Adamus" },
      { id: "sarah", label: "Sarah" },
    ],
  },
  {
    id: "theme-grief",
    kind: "theme",
    name: "Grief and healing",
    epithet: "Let it heal",
    art: "/art/hospital.jpg",
    summary: "Grief is not a failure of love. It is love with nowhere to put its hands.",
    body: "Sarah's death opens the story. Healing does not erase her. It lets her remain as light that can, for a moment, be held. The Orb prefers this work to any throne.",
    links: [
      { id: "sarah", label: "Sarah" },
      { id: "orb", label: "The Orb" },
      { id: "nancy", label: "Nancy" },
    ],
  },
  {
    id: "theme-will",
    kind: "theme",
    name: "Free will versus perfection",
    epithet: "Why Terra is wild",
    art: "/art/codex/elysium.jpg",
    summary: "Elysium proved that a kind cage is still a cage.",
    body: "Nevaeh is harmony earned. Earth is trial. The point is not to pick a winner. The point is that love without choice is only display.",
    links: [
      { id: "elysium", label: "Elysium" },
      { id: "earth", label: "Earth" },
      { id: "nevaeh", label: "Nevaeh" },
    ],
  },
  {
    id: "theme-intent",
    kind: "theme",
    name: "Pure intent versus control",
    epithet: "Open hand, closed hand",
    art: "/art/orb.jpg?v=front",
    summary: "The Orb will not work for a fist.",
    body: "Samael wants both worlds managed. Nancy wants them mended. Large miracles cost fire because they must be meant. Control is cheaper, and it never lights.",
    links: [
      { id: "orb", label: "The Orb" },
      { id: "samael", label: "Samael" },
      { id: "grail", label: "The Grail" },
    ],
  },
  {
    id: "theme-love",
    kind: "theme",
    name: "Love that crosses worlds",
    epithet: "The true ending",
    art: "/art/epilogue.jpg",
    summary: "Love can cross dimensions, time, and the gap between Earth and Nevaeh.",
    body: "The win was never domination. The win was reunion. A gold thread holds when a sword would cut. That is the whole map.",
    links: [
      { id: "bridge", label: "The Bridge" },
      { id: "nancy", label: "Nancy" },
      { id: "sarah", label: "Sarah" },
    ],
  },
];

export const TIMELINE: TimelineBeat[] = [
  {
    id: "t1",
    n: 1,
    title: "Elysium declines",
    text: "Abundance without freedom grows heavy. Kindness becomes a noose.",
    linkId: "elysium",
  },
  {
    id: "t2",
    n: 2,
    title: "A new universe, and time",
    text: "Adamus opens an empty sky and gives it a clock so love can grow.",
    linkId: "first-world",
  },
  {
    id: "t3",
    n: 3,
    title: "Nevaeh is founded",
    text: "A perfected sister world is raised in the Pleiades.",
    linkId: "nevaeh",
  },
  {
    id: "t4",
    n: 4,
    title: "Terra is seeded",
    text: "Earth is planted as the wilder twin: free will, mortality, trial.",
    linkId: "earth",
  },
  {
    id: "t5",
    n: 5,
    title: "Civil war",
    text: "Zorath's hunger splits the old peace. Samael flees toward Earth.",
    linkId: "samael",
  },
  {
    id: "t6",
    n: 6,
    title: "33 AD",
    text: "Sananda walks Terra and leaves the Spark at Qumran.",
    linkId: "sananda",
  },
  {
    id: "t7",
    n: 7,
    title: "Two thousand years",
    text: "Guardians keep watch. The Shadow practices division. Neither sleeps.",
    linkId: "glasses",
  },
  {
    id: "t8",
    n: 8,
    title: "Present",
    text: "Nancy finds the Orb. Grief and a Brooklyn kitchen become a cosmology.",
    linkId: "nancy",
  },
  {
    id: "t9",
    n: 9,
    title: "The bridge opens",
    text: "Love completes what power could not. A gold thread holds.",
    linkId: "bridge",
  },
];

export const GROUPS: { id: NonNullable<CodexEntry["group"]>; label: string }[] = [
  { id: "family", label: "The Family" },
  { id: "nevaeh", label: "Of Nevaeh" },
  { id: "shadow", label: "The rival line" },
  { id: "crew", label: "Crew of Genesis" },
  { id: "earth", label: "On Earth" },
];

export const BY_ID: Record<string, CodexEntry> = Object.fromEntries(ENTRIES.map((e) => [e.id, e]));

export function searchEntries(q: string, starred: string[] | null): CodexEntry[] {
  const query = q.trim().toLowerCase();
  return ENTRIES.filter((e) => {
    if (starred && !starred.includes(e.id)) return false;
    if (!query) return true;
    const hay = `${e.name} ${e.epithet} ${e.summary} ${e.body} ${e.loveLine ?? ""} ${e.relations ?? ""}`.toLowerCase();
    return hay.includes(query);
  });
}
