const DEFS: Record<string, string> = {
  STAR: "A bright point of light in the night sky.",
  MOON: "The round body that orbits the Earth.",
  HOPE: "A feeling that something good may happen.",
  LOVE: "A strong feeling of care for someone.",
  FIRE: "Heat and flame that burns.",
  RAIN: "Water falling from clouds.",
  WIND: "Moving air you can feel.",
  SONG: "Music made of words and tune.",
  BOOK: "Pages bound together to be read.",
  TREE: "A tall plant with a wooden trunk.",
  BLUE: "The colour of a clear daytime sky.",
  PINK: "A light reddish colour.",
  GOLD: "A precious yellow metal.",
  CITY: "A large town with many people.",
  HOME: "The place where you live.",
  KIND: "Friendly and caring toward others.",
  PLAY: "To take part in a game or fun.",
  JUMP: "To push off the ground into the air.",
  CAVE: "A hollow space in rock or earth.",
  GATE: "A door in a fence or wall.",
  PATH: "A track for walking.",
  LAMP: "A light you can switch on.",
  SHIP: "A large boat for the sea.",
  BIRD: "An animal with wings and feathers.",
  FISH: "An animal that lives in water.",
  WOLF: "A wild animal related to the dog.",
  BEAR: "A large furry wild animal.",
  RING: "A circle of metal worn on a finger.",
  SNOW: "Soft white ice that falls in winter.",
  LEAF: "A flat green part of a plant.",
  ROSE: "A flower, often with thorns.",
  LION: "A large wild cat with a mane.",
  PEAR: "A sweet fruit, wider at the bottom.",
  CAKE: "A sweet baked dessert.",
  MILK: "A white drink from cows.",
  BELL: "A metal cup that rings when struck.",
  DRUM: "A round instrument you hit to make a beat.",
  NOTE: "A single musical sound, or a short message.",
  WAVE: "A moving ridge of water in the sea.",
  SAND: "Tiny grains found on a beach.",
  HILL: "A raised piece of land, smaller than a mountain.",
  LAKE: "A body of water surrounded by land.",
  PARK: "Open land for rest and play.",
  HERO: "Someone brave who helps others.",
  GLOW: "A soft steady light.",
  NEON: "A very bright glowing colour.",
  ROCK: "A hard piece of stone.",
  SEED: "The part of a plant that can grow a new one.",
  DOOR: "A panel that opens into a room.",
  WALL: "A solid side of a room or building.",
  ROAD: "A way built for travel.",
  BOAT: "A small craft that travels on water.",
  KITE: "A light frame flown on a string in the wind.",
  COIN: "A small metal disc used as money.",
  MASK: "A covering worn on the face.",
  TENT: "A cloth shelter used outdoors.",
  FORK: "A tool with prongs for eating.",
  BOWL: "A round deep dish.",
  SOAP: "Used with water to wash.",
  WOOL: "Soft fibre from sheep, used for clothes.",
  HEART: "The organ that pumps blood, or a symbol of love.",
  LIGHT: "What lets us see; brightness.",
  CLOUD: "A mass of tiny water drops in the sky.",
  STORM: "Strong wind with rain or thunder.",
  RIVER: "A long stream of fresh water.",
  OCEAN: "A huge body of salt water.",
  EARTH: "The planet we live on, or soil.",
  MUSIC: "Sound arranged in a pleasing way.",
  DANCE: "To move your body to a beat.",
  SMILE: "A happy look on the face.",
  DREAM: "Pictures in the mind while you sleep.",
  MAGIC: "Wonder that seems impossible.",
  PEACE: "Calm, without fighting.",
  FAITH: "Trust or belief.",
  CROWN: "A royal headpiece.",
  SWORD: "A long bladed weapon.",
  STONE: "Hard rock, or a small piece of it.",
  FLAME: "The visible part of a fire.",
  SPARK: "A tiny flash of fire or light.",
  ORBIT: "The path of one body around another.",
  COMET: "A space object with a glowing tail.",
  TIGER: "A large striped wild cat.",
  HORSE: "A large animal people can ride.",
  EAGLE: "A powerful bird of prey.",
  WHALE: "A huge mammal that lives in the sea.",
  CORAL: "A hard colourful growth in the ocean.",
  APPLE: "A round fruit, often red or green.",
  BREAD: "A baked food made from flour.",
  HONEY: "Sweet food made by bees.",
  BERRY: "A small juicy fruit.",
  GRAPE: "A small fruit that grows in bunches.",
  LEMON: "A sour yellow citrus fruit.",
  MAPLE: "A tree known for sweet sap.",
  IVORY: "A creamy-white colour or material.",
  PEARL: "A smooth gem formed in a shell.",
  PIANO: "A keyboard instrument with strings inside.",
  FLUTE: "A wind instrument you blow across.",
  STAGE: "A raised floor for a performance.",
  STORY: "A tale that is told or written.",
  NOVEL: "A long book of fiction.",
  SHINE: "To give off bright light.",
  LEVEL: "A stage of a game, or how high something is.",
  SCORE: "Points earned in a game.",
  TIMER: "A device that counts time.",
  FIELD: "Open land, often with grass.",
  GROVE: "A small group of trees.",
  BRAVE: "Ready to face danger or fear.",
  PRIDE: "A feeling of being pleased with yourself.",
  GRACE: "Elegant movement, or kindness.",
  CHARM: "A pleasing quality, or a lucky object.",
  DRUMS: "Percussion instruments you hit.",
  PLANT: "A living thing that grows from the ground.",
  WATER: "The clear liquid we drink.",
  PAPER: "Thin sheets used for writing.",
  GLASS: "A hard clear material, or a drinking cup.",
  CHAIR: "A seat for one person.",
  TABLE: "A flat surface with legs.",
  CLOCK: "A device that shows the time.",
  BRUSH: "A tool with bristles for painting or hair.",
  PAINT: "Coloured liquid used to cover a surface.",
  VOICE: "The sound you make when you speak or sing.",
  SOUND: "Something you can hear.",
  NIGHT: "The dark hours after sunset.",
  PLANET: "A large world that orbits a star.",
  GALAXY: "A huge group of stars.",
  CASTLE: "A large fortified building.",
  KNIGHT: "A warrior of old in armour.",
  DRAGON: "A mythical winged fire-breathing creature.",
  TEMPLE: "A building used for worship.",
  BRIDGE: "A structure that carries you over a gap.",
  GARDEN: "A place where plants are grown.",
  FOREST: "A large area of trees.",
  MEADOW: "A field of grass and flowers.",
  STREAM: "A small flowing river.",
  ISLAND: "Land with water all around it.",
  DESERT: "A very dry sandy or rocky place.",
  SUMMER: "The warmest season of the year.",
  WINTER: "The coldest season of the year.",
  SPRING: "The season when plants begin to grow.",
  AUTUMN: "The season when leaves fall.",
  FRIEND: "Someone you like and trust.",
  FAMILY: "People related to you.",
  SISTER: "A girl who has the same parents as you.",
  MOTHER: "A female parent.",
  FATHER: "A male parent.",
  SCHOOL: "A place where students learn.",
  PENCIL: "A tool for writing or drawing.",
  GUITAR: "A stringed instrument you strum.",
  VIOLIN: "A small stringed instrument played with a bow.",
  MELODY: "A tune you can sing or hum.",
  CHORUS: "The repeated part of a song.",
  LYRICS: "The words of a song.",
  CAMERA: "A device that takes photographs.",
  CANVAS: "Strong cloth used for painting.",
  SKETCH: "A quick drawing.",
  PUZZLE: "A problem or game to work out.",
  RIDDLE: "A word puzzle with a clever answer.",
  SECRET: "Something kept hidden.",
  SHADOW: "A dark shape made when light is blocked.",
  SILVER: "A shiny grey-white metal.",
  GOLDEN: "Coloured like gold.",
  PURPLE: "A colour between red and blue.",
  ORANGE: "A colour, or a round citrus fruit.",
  YELLOW: "The colour of a ripe lemon.",
  VIOLET: "A purple flower, or that colour.",
  MIRROR: "A glass that shows your reflection.",
  HELMET: "A hard hat that protects the head.",
  ANCHOR: "A heavy hook that holds a ship in place.",
  SAILOR: "A person who works on a ship.",
  ROCKET: "A craft that flies into space.",
  METEOR: "A space rock that burns in the sky.",
  KITTEN: "A young cat.",
  PUPPY: "A young dog.",
  RABBIT: "A small animal with long ears.",
  TURTLE: "A reptile with a hard shell.",
  FALCON: "A fast hunting bird.",
  BUTTON: "A small disc that fastens clothes, or a control you press.",
  WINDOW: "An opening in a wall with glass.",
  CANDLE: "Wax with a wick that burns to give light.",
  MARKET: "A place where goods are bought and sold.",
  CIRCLE: "A round shape.",
  SQUARE: "A shape with four equal sides.",
  SPIRAL: "A curve that winds around a centre.",
  RIBBON: "A narrow strip of cloth or paper.",
  POCKET: "A small bag sewn into clothes.",
  RAINBOW: "An arc of colours in the sky after rain.",
  THUNDER: "The loud boom that follows lightning.",
  HARMONY: "Notes that sound good together, or peaceful agreement.",
  COURAGE: "Bravery in the face of fear.",
  FREEDOM: "The right to act and live without unfair limits.",
  JUSTICE: "Fairness and right treatment.",
  KINGDOM: "A land ruled by a king or queen.",
  FORTUNE: "Luck, or a large amount of wealth.",
  MYSTERY: "Something that is not yet explained.",
  JOURNEY: "Travel from one place to another.",
  HORIZON: "The line where sky and earth seem to meet.",
  SUNRISE: "The time when the sun first appears.",
  LIBRARY: "A place full of books to read or borrow.",
  CHAPTER: "A section of a book.",
  PICTURE: "An image, photo, or drawing.",
  DRAWING: "A picture made with pencil or pen.",
  SINGING: "Making music with your voice.",
  DANCING: "Moving your body to music.",
  RUNNING: "Moving quickly on your feet.",
  WARRIOR: "A skilled fighter.",
  DIAMOND: "A very hard, sparkling gem.",
  EMERALD: "A bright green gem.",
  PENGUIN: "A bird that swims but does not fly.",
  GIRAFFE: "A tall animal with a very long neck.",
  PANTHER: "A large black wild cat.",
  LEOPARD: "A spotted wild cat.",
  OCTOPUS: "A sea animal with eight arms.",
  SCIENCE: "The study of how the world works.",
  HISTORY: "The story of what happened in the past.",
  NUMBERS: "Symbols used for counting.",
  PUZZLES: "Problems or games to solve.",
  RIDDLES: "Tricky questions with clever answers.",
  SECRETS: "Things that are kept hidden.",
  BROTHER: "A boy who has the same parents as you.",
  POPPIES: "Bright flowers, often red.",
  DOLPHIN: "A smart sea mammal that leaps in waves.",
  CRYSTAL: "A clear, sparkling mineral.",
  LANTERN: "A portable lamp with a cover.",
  BLOSSOM: "A flower, especially on a tree.",
  THISTLE: "A prickly wild plant.",
  GLIMMER: "A faint unsteady light.",
  SPARKLE: "To shine with little flashes.",
  WHISPER: "To speak very softly.",
  BLANKET: "A warm cover for a bed.",
  CUSHION: "A soft pad for sitting.",
  KITCHEN: "The room where food is cooked.",
  GARDENS: "Places where plants are grown.",
  STARSHIP: "A craft imagined for travel in space.",
  MOONBEAM: "A ray of light from the moon.",
  SUNSHINE: "Light and warmth from the sun.",
  DAYBREAK: "The first light of morning.",
  MIDNIGHT: "Twelve o'clock at night.",
  UNIVERSE: "All of space and everything in it.",
  ASTEROID: "A rocky body orbiting the sun.",
  TREASURE: "Valuable things that are hidden or found.",
  KINGDOMS: "Lands ruled by kings or queens.",
  WARRIORS: "People trained to fight.",
  CHAMPION: "The winner of a contest.",
  FRIENDLY: "Kind and easy to get along with.",
  KINDNESS: "The quality of being kind.",
  LAUGHTER: "The sound people make when they find something funny.",
  BASEBALL: "A bat-and-ball sport.",
  FOOTBALL: "A team sport played with a ball and goals.",
  SWIMMING: "Moving through water using your arms and legs.",
  PAINTING: "A picture made with paint.",
  SKETCHES: "Quick drawings.",
  MELODIES: "Tunes you can sing.",
  SYMPHONY: "A long piece of music for an orchestra.",
  ELEPHANT: "A huge land animal with a trunk.",
  KANGAROO: "An Australian animal that hops.",
  MOUNTAIN: "A very high piece of land.",
  SEASHORE: "The land along the edge of the sea.",
  SANDWICH: "Food between two pieces of bread.",
  PANCAKES: "Thin round cakes cooked in a pan.",
  LEMONADE: "A sweet drink made with lemon.",
  NOTEBOOK: "A book of blank pages for writing.",
  BACKPACK: "A bag worn on the back.",
  HOMEWORK: "School work done at home.",
  TWILIGHT: "The soft light just after sunset.",
  CRYSTALS: "Clear sparkling minerals.",
  FIREWORK: "A colourful exploding light in the sky.",
  SNOWBALL: "A ball packed from snow.",
  RAINCOAT: "A coat that keeps you dry in rain.",
  FOOTSTEP: "The sound or mark of a foot on the ground.",
  DOORSTEP: "The step just outside a door.",
  MOONRISE: "The time when the moon appears.",
  STARFISH: "A star-shaped sea animal.",
  SEASHELL: "The hard covering of a sea creature.",
  COUNTDOWN: "Counting down the seconds to a start.",
  CONUNDRUM: "A puzzling question or problem.",
  ADVENTURE: "An exciting or daring experience.",
  CHAMPIONS: "Winners of a contest.",
  STARLIGHT: "Light that comes from the stars.",
  MOONLIGHT: "Light that comes from the moon.",
  SUNFLOWER: "A tall plant with a large yellow flower.",
  BUTTERFLY: "An insect with colourful wings.",
  WATERFALL: "Water falling from a high place.",
  MOUNTAINS: "Very high pieces of land.",
  SPACESHIP: "A craft that travels in space.",
  TELESCOPE: "A tube that makes distant things look closer.",
  WONDERFUL: "Extremely good or amazing.",
  BEAUTIFUL: "Very pleasing to look at.",
  BRILLIANT: "Very bright, or very clever.",
  FANTASTIC: "Wonderful; almost too good to be true.",
  CHOCOLATE: "A sweet brown food made from cacao.",
  BLUEBERRY: "A small dark-blue fruit.",
  STORYBOOK: "A book of stories.",
  FAIRYTALE: "A magical story, often for children.",
  DAYDREAMS: "Pleasant thoughts while you are awake.",
  NIGHTFALL: "The coming of night.",
  AFTERNOON: "The time between midday and evening.",
  STARSHIPS: "Craft imagined for travel in space.",
  HONEYBEES: "Bees that make honey.",
  AMAZEMENT: "A feeling of great surprise.",
  LIGHTNING: "A flash of electricity in a storm.",
  SNOWFLAKE: "A tiny unique crystal of snow.",
  CANDLELIT: "Lit by the glow of candles.",
  MOONBEAMS: "Rays of light from the moon.",
  RAINSTORM: "Heavy rain with wind.",
  FIREFLIES: "Insects that glow at night.",
  WHIRLPOOL: "Water spinning in a circle.",
  CLOCKWORK: "The gears that make a clock run.",
  PATCHWORK: "Cloth sewn from many pieces.",
};

export function meaning(word: string): string {
  return DEFS[word.toUpperCase()] ?? "A word made from these letters.";
}
